- name: Launch EC2 instance
  amazon.aws.ec2_instance:
    name: my-webserver
    key_name: "{{ key_name }}"
    instance_type: t2.micro
    image_id: ami-0abcdef1234567890
    wait: yes
    security_groups: [ "my-sg" ]
  register: ec2_instance

- name: Add new instance to in-memory inventory
  ansible.builtin.add_host:
    hostname: "{{ ec2_instance.instances[0].public_ip }}"
    groups: webservers
    ansible_user: ec2-user
    ansible_ssh_private_key_file: "~/.ssh/{{ key_name }}.pem"

- name: Configure webserver
  hosts: webservers
  become: yes
  tasks:
    - name: Install Apache
      ansible.builtin.yum:
        name: httpd
        state: present
